### ISSUE TITLE
POtential adoption of the book as a textbook

### ISSUE THREAD

**Issue by olekmali** [PacktPublishing/Industrial-Cybersecurity-Second-Edition#1]
Is there any way to request electronic materials for PowerPoint or PDF presentation to be used in a course that is based on "Industrial Cybersecurity: Efficiently monitor the cybersecurity posture of your ICS environment, 2nd Edition 2nd ed. Edition" by Pascal Ackerman as a required textbook?

**Comment by shruthis-shetty** [comment]
Hi @olekmali , I hope you got the solution to this issue.
