### ISSUE TITLE
Where is the Chapter 15 pdf?

### ISSUE THREAD

**Issue by dskram1** [PacktPublishing/Industrial-Cybersecurity-Second-Edition#2]
In chapter 15, the second edition states that the chapter 15 pdf is available on github. Where is it? I don't see it anywhere.

**Comment by nithikpackt** [comment]
Hi @dskram1 , Chapter15 is available in this repository, Here's the link to it : [Chapter15](https://github.com/PacktPublishing/Industrial-Cybersecurity-Second-Edition/blob/main/Chapter_15_Industrial_Control_System_Risk_Assessments.pdf )
